### PR TITLE
Fixes #301 - adds hwm "push tab"

### LINKED ISSUE #301: Allow HWM to be toggled
Should behave same as peak labels

### PR DESCRIPTION
**Pull request by 09Kathy**
Not sure if I like 'HWM' at the front of every label - maybe it's necessary to easily differentiate from peaks. I can remove it if you want.
image

### CODE REVIEW

**Comment by HansVraga** [comment]
Maybe we can style the labels differently between high water marks and peaks? Keep the color of the hwm or peak symbol?

**Comment by 09Kathy** [comment]
Yeah, I think that could be better. Something like this: 
image
The labels are almost always directly on top of each other, so either way, it works best to view one label type at a time

**Comment by 09Kathy** [comment]
though I do like the white background better as stand alone. I'll play around with a few other things too

**Comment by 09Kathy** [comment]
image

**Comment by lprivette** [comment]
I like the color reflecting the symbol's color too. What if we change the direction of one of the labels to left? so that hwm labels would be on the left of their icon and peak labels would be to the right of their icon.

**Pull request closed without merging**
